language: objective-c

install:
  - bundle install
  - bundle exec pod install
  - npm install -g appium
before_script:
  - appium &
script:
  - ./gradlew check
after_script:
  - ps -ef | grep appium | grep -v grep | tr -s " " | cut -d " " -f 3 | xargs -n 1 kill
