language: objective-c
osx_image: xcode6.4

env:
  global:
    - TERM=dumb

cache:
  bundler: true
  directories:
    - $HOME/.gradle
    - $HOME/.npm

install:
  - bundle install
  - bundle exec pod install
  - npm install -g appium
before_script:
  - appium &
script:
  - ./gradlew clean test --debug
after_script:
  - ps -ef | grep appium | grep -v grep | tr -s " " | cut -d " " -f 3 | xargs -n 1 kill
